CORE: SME: ignore unused parameter
Ignore unused paramater to avoid build fail with -Werror=unused-but-set-parameter.
Build error log:
  error: parameter ‘status’ set but not used [-Werror=unused-but-set-parameter]