CORE: SERVICES: COMMON: fix "MIN"/"MAX" redefined error for kernel > 6.11
MIN() and MAX() macros are defined at $KERNEL_SRC/include/linux/minmax.h
after kernel 6.11 by this commit:
  1a251f52cfdc minmax: make generic MIN() and MAX() macros available everywhere

Build error log:
  osdep_adf.h:965: error: "MIN" redefined [-Werror]
  osdep_adf.h:966: error: "MAX" redefined [-Werror]