CORE: HDD: fix error: implicit declaration of function ‘strlcpy’ for kernel > 6.7
After kernel 6.7, strlcpy() is removed, and use long live strscpy().
According with kernel commit:
  d2627006 string: Remove strlcpy()